Ceejay/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Adminapp.urls')),
    path('staff/', include('Staffapp.urls')),
] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

Staffapp/urls.py
from django.urls import path
from Staffapp import views

app_name = 'staff'
urlpatterns = [
    path('add_booking',views.add_booking, name='add_booking'),
    path('edit_booking/<int:booking_id>',views.edit_booking,name='edit_booking'),
    path('add_despatch',views.add_despatch, name='add_despatch'),
    path('add_delivery',views.add_delivery, name='add_delivery'),
]

templates/add_booking.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="form-row">
        <div>
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name="date" style="width: 200px;">
        </div>
        <div>
            <label for="consignor_name" style="margin-left: 50px;">Consignor Name</label>
            <select id="consignor_name" style="margin-left: 50px;" class="form-control" name="consignor" onchange="updateConsignorDetails()">
                <option value="">Select Consignor</option>
                {% for x in data1 %}
                    <option value="{{ x.consignor_id }}" data-address="{{ x.consignor_address }}" data-phone="{{ x.consignor_phone }}">
                        {{ x.consignor_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="consignor_address" style="margin-left: 80px;">Consignor Address</label>
            <input type="text" class="form-control" id="consignor_address" style="width: 400px; margin-left: 80px;" readonly>
        </div>
        <div>
            <label for="consignor_phone" style="margin-left: 40px;">Consignor Phone Number</label>
            <input type="text" class="form-control" id="consignor_phone" name="phone_number" style="margin-left: 40px;" readonly>
        </div>
    </div>
    <div class="form-row">
        <div>
            <label for="consignee_name" style="margin-top:10px">Consignee Name</label>
            <select id="consignee_name" class="form-control"  name="consignee" onchange="updateConsigneeDetails()">
                <option value="">Select Consignee</option>
                {% for x in data2 %}
                    <option value="{{ x.consignee_id }}" data-address="{{ x.consignee_address }}" data-phone="{{ x.consignee_phone }}">
                        {{ x.consignee_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="consignee_phone" style="margin-left: 50px; margin-top:10px">Consignee Phone Number</label>
            <input type="text" name="phone_number" class="form-control" id="consignee_phone" style="width: 200px; margin-left: 50px;" readonly>
        </div>
        <div>
            <label for="consignee_address" style="margin-left: 50px; margin-top:10px">Consignee Address</label>
            <input type="text" name="consignee_address" class="form-control" id="consignee_address" style="width: 400px;  margin-left: 50px;" readonly>
        </div>
        <div>
            <label for="district_name" style="margin-left: 40px; margin-top:10px">Destination</label>
            <select id="district_name" style="margin-left: 40px;" class="form-control" name="district" required>
                <option value="">Select District</option>
                {% for x in data3 %}
                    <option value="{{ x.district_id}}">
                        {{ x.district_name}}
                    </option>
                {% endfor %}
            </select>
            <a href="/add_district" style="margin-left:40px;">add destination?</a>
        </div>
    </div>
    <div class="form-row">
        <div>
            <label for="noOfBoxes" style="margin-top:10px">No. of Boxes</label>
            <input type="number" class="form-control" id="noOfBoxes" style="width: 100px; " name="number">
        </div>
        <div>
            <label for="weight" style="margin-left: 30px;  margin-top:10px">Weight(Kg)</label>
            <input type="text" class="form-control" id="weight" style="width: 100px; margin-left: 30px;" name="weight">
        </div>
        <div>
            <label for="price" style="margin-left: 30px;margin-top:10px">Price</label>
            <input type="text" class="form-control" id="price" style="width: 100px; margin-left: 30px;" name="price" readonly>
        </div>
        <div>
            <label for="remarks" style="margin-left: 50px;margin-top:10px">Remarks</label>
            <input type="text" class="form-control" id="remarks" style="width: 400px; margin-left: 50px;" name="remark">
        </div>
    </div><br>
    <button type="submit" class="btn btn-secondary" style="background-color: #dc3545;">Save</button>
</form>
{% endblock %}

templates/add_delivery.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-3">
            <label for="date">Date:</label>
            <input type="date" class="form-control" id="date" name="date">
        </div>
<!--        <form method = "POST">-->
<!--            {% csrf_token%}-->
        <div class="form-group col-md-4">
            <label for="booking_id">Booking No.:</label>
            <input type="text" class="form-control" id="bookings_id" name="booking_id">
        </div>
            <div class="form-row">
        <div class="form-group col-md-2">
            <button type="submit" class="btn btn-save" style="background-color:#d9534f; margin-top:30px;">Check</button>
        </div>
        </div>
<!--            </form>-->
        <div class="table-container" style="margin-bottom: 20px;">
        <table class="table table-bordered table-striped table-hover" style="margin-top:20px;margin-right:120px;">
            <thead>
            <tr>
                <th>#</th>
                <th><input type="checkbox"></th>
                <th>Date</th>
                <th>Booking number</th>
                <th>Consignor</th>
                <th>Consignee</th>
                <th>Weight</th>
                <th>Number of boxes</th>
                <th>Price</th>
            </tr>
            </thead>
            <tbody>
            {% for x in data1%}
                <tr>
<!--                    {% if x.booking_id != data2.booking.booking_id %}-->
                    <td>{{forloop.counter}}</td>
                    <td><input type="checkbox" name="booking_id" id="booking_id" value="{{x.booking_id}}"></td>
                    <td>{{x.date_booked|date:"d/m/y"}}</td>
                    <td>{{x.booking_id}}</td>
                    <td>{{x.consignor.consignor_name}}</td>
                    <td>{{x.consignee.consignee_name}}</td>
                    <td>{{x.weight}}</td>
                    <td>{{x.number_of_boxes}}</td>
                    <td>{{x.price}}</td>
                    {%endif%}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="delivered" name="del_status">
                <label class="form-check-label" for="delivered">
                    Delivered
                </label>
            </div>
        </div>
        <div class="form-group col-md-2">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" id="returned" name="ret_status">
                <label class="form-check-label" for="returned">
                    Returned
                </label>
            </div>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-2">
            <button type="submit" class="btn btn-save" style="background-color:#d9534f; padding: 10px 20px;">Save</button>
        </div>
    </div>
</form>
{% endblock %}

templates/add_despatch.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="form-row">
        <div class="form-group col-md-4">
            <label for="date">Date:</label>
            <input type="date" class="form-control" id="date" name="date">
        </div>
        <div class="form-group col-md-4">
            <label for="driver_name">Driver:</label>
            <select id="driver_name" name="driver" required style="width:410px;height:38px;background-color:white">
                {% for x in data2 %}
                <option value="{{x.driver_id}}">{{x.driver_name}}</option>
                {%endfor%}
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="vehicle_name">Vehicle:</label>
            <select id="vehicle_name" name="vehicle" required style="width:410px;height:38px;background-color:white;">
                {% for x in data3 %}
                <option value="{{x.vehicle_id}}">{{x.vehicle_number}}</option>
                {%endfor%}
            </select>
        </div>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th><input type="checkbox"></th>
                <th>Booking Date</th>
                <th>Booking No.</th>
                <th>Consignor</th>
                <th>Consignee</th>
                <th>Destination</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                {% if data4.booking.booking_id != x.booking_id%}
                    <td>{{forloop.counter}}</td>
                    <td><input type="checkbox" name="booking" id="booking_id" value="{{x.booking_id}}"></td>
                    <td>{{x.date_booked|date:"d/m/y"}}</td>
                    <td>{{x.booking_id}}</td>
                    <td>{{x.consignor.consignor_name}}</td>
                    <td>{{x.consignee.consignee_name}}</td>
                    <td>{{x.district.district_name}}</td>
                    <td>{{x.number_of_boxes}}</td>
                    <td>{{x.price}}</td>
                    <td>{{x.status}}</td>
                {% endif %}
            </tr>
        {%endfor%}
        </tbody>
    </table>
    <button type="submit" class="btn btn-secondary" style="background-color: #dc3545;">Save</button>
</form>
{% endblock %}

templates/add_district.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST" name="consignor">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="district_name">District:</label>
            <input type="text" class="form-control" id="district_name" name="district_name">
        </div>
        <div class="form-group col-md-6">
            <label for="state">State:</label>
            <input type="text" class="form-control" id="state" name="state">
        </div>
    </div>

    <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Save</button>

</form>
{% endblock %}

templates/edit_booking.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="form-row">
        <div>
            <label for="date">Date</label>
            <input type="date" class="form-control" id="date" name="date" style="width: 200px;" value="{{data1.date_booked}}">
        </div>
        <div>
            <label for="consignor_name" style="margin-left: 50px;">Consignor Name</label>
            <select id="consignor_name" style="margin-left: 50px;" class="form-control" name="consignor" onchange="updateConsignorDetails()">
                <option value="">Select Consignor</option>
                {% for x in data2%}
                    <option value="{{ x.consignor_id }}" data-address="{{ x.consignor_address }}" data-phone="{{ x.consignor_phone }}">
                        {{ x.consignor_name }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <div>
            <label for="consignor_address" style="margin-left: 80px;">Consignor Address</label>
            <input type="text" class="form-control" id="consignor_address" style="width: 400px; margin-left: 80px;" readonly value="{{data1.consignor.consignor_address}}">
        </div>
        <div>
            <label for="consignor_phone" style="margin-left: 40px;">Consignor Phone Number</label>
            <input type="text" class="form-control" id="consignor_phone" name="phone_number" style="margin-left: 40px;" readonly value="{{data1.consignor.consignor_phone}}">
        </div>
    </div>
    <div class="form-row">
        <div>
            <label for="consignee_name" style="margin-top:10px">Consignee Name</label>
            <select id="consignee_name" class="form-control"  name="consignee" onchange="updateConsigneeDetails()">
                <option value="">Select Consignee</option>
                {% for x in data3%}
                    <option value="{{ x.consignee_id }}" data-address="{{ x.consignee_address }}" data-phone="{{ x.consignee_phone }}">
                        {{ x.consignee_name }}
                    </option>
                {%endfor%}
            </select>
        </div>
        <div>
            <label for="consignee_phone" style="margin-left: 50px; margin-top:10px">Consignee Phone Number</label>
            <input type="text" name="phone_number" class="form-control" id="consignee_phone" style="width: 200px; margin-left: 50px;" readonly value="{{data1.consignee.consignee_phone}}">
        </div>
        <div>
            <label for="consignee_address" style="margin-left: 50px; margin-top:10px">Consignee Address</label>
            <input type="text" name="consignee_address" class="form-control" id="consignee_address" style="width: 400px;  margin-left: 50px;" readonly value="{{data1.consignee.consignee_address}}">
        </div>
        <div>
            <label for="district_name" style="margin-left: 40px; margin-top:10px">Destination</label>
            <select id="district_name" style="margin-left: 40px;" class="form-control" name="district" required>
                <option value="">Select District</option>
                {% for x in data4 %}
                    <option value="{{ x.district_id}}">
                        {{ x.district_name}}
                    </option>
                {% endfor %}
            </select>
            <a href="/add_district" style="margin-left:40px;">add destination?</a>
        </div>
    </div>
    <div class="form-row">
        <div>
            <label for="noOfBoxes" style="margin-top:10px">No. of Boxes</label>
            <input type="number" class="form-control" id="noOfBoxes" style="width: 100px; " name="number" value="{{data1.number_of_boxes}}" >
        </div>
        <div>
            <label for="weight" style="margin-left: 30px;  margin-top:10px">Weight(Kg)</label>
            <input type="text" class="form-control" id="weight" style="width: 100px; margin-left: 30px;" name="weight" value="{{data1.weight}}">
        </div>
        <div>
            <label for="price" style="margin-left: 30px;margin-top:10px">Price</label>
            <input type="text" class="form-control" id="price" style="width: 100px; margin-left: 30px;" name="price" readonly value="{{data1.price}}">
        </div>
        <div>
            <label for="remarks" style="margin-left: 50px;margin-top:10px">Remarks</label>
            <input type="text" class="form-control" id="remarks" style="width: 400px; margin-left: 50px;" name="remark" value="{{data1.remark}}">
        </div>
    </div><br>
    <button type="submit" class="btn btn-secondary" style="background-color: #dc3545;">Save</button>
</form>
{% endblock %}

templates/edit_consignor.html
{% extends 'dashboard.html' %}
{% block content %}
{% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
<form method="POST" name="consignor">
    {% csrf_token %}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="consignor_name">Consignor Name:</label>
            <input type="text" class="form-control" id="consignor_name" name="consignor_name" value="{{data.consignor_name}}">
        </div>
        <div class="form-group col-md-6">
            <label for="address">Consignor address:</label>
            <input type="text" class="form-control" id="address" name="consignor_address" value="{{data.consignor_address}}">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="phone_number">Phone Number:</label>
            <input type="tel" class="form-control" id="phone_number" name="consignor_phone" value="{{data.consignor_phone}}">
        </div>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="status" value="{{data.consignor_status}}" name="consignor_status" checked>
        <label class="form-check-label" for="status" >Active Consignor</label>
    </div>
    <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Save</button>
</form>
{% endblock %}

templates/edit_driver.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST" name="consignor">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="driver_name">Diver Name:</label>
            <input type="text" class="form-control" id="driver_name" name="driver_name" value="{{data1.driver_name}}">
        </div>
        <div class="form-group col-md-6">
            <label for="driver_address">Address:</label>
            <input type="text" class="form-control" id="driver_address" name="driver_address" value="{{data1.driver_address}}">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="driver_phone">Phone Number:</label>
            <input type="tel" class="form-control" id="driver_phone" name="driver_phone" value="{{data1.driver_phone}}">
        </div>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" value="{{data1.driver_status}}" id="status" name="driver_status" checked>
        <label class="form-check-label" for="status" >Active Consignor</label>
    </div>
    <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Save</button>

</form>
{% endblock %}

templates/list_booking.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="consignorName">Consignor name:</label>
        <input type="text" id="consignorName" name="search">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered" id="despatchTable">
        <thead>
        <tr>
            <th>Date</th>
            <th>LR No.</th>
            <th>Consignor</th>
            <th>Consignee</th>
            <th>Destination</th>
            <th>Weight</th>
            <th>No.of Boxes</th>
            <th>Price</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.date_booked|date:"d/m/y"}}</td>
                <td><a href="/pod_details/{{x.booking_id}}">{{x.booking_id}}</a> </td>
                <td>{{x.consignor.consignor_name}}</td>
                <td>{{x.consignee.consignee_name}}</td>
                <td>{{x.district.district_name}}</td>
                <td>{{x.weight}}kg</td>
                <td>{{x.number_of_boxes}}</td>
                <td>{{x.price}}</td>
                <td>{{x.status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href="{% url 'staff:edit_booking' x.booking_id %}"><ion-icon name="create-outline"></ion-icon></a></button>
                    {% if data.designation.designation == 'Admin'%}
                        <button class="btn btn-sm btn-danger"><a href=/delete_booking/{{x.booking_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="pagination">
    <span class="step-links">
        {% if data1.has_previous %}
            <a href="?page=1">First</a>
            <a href="?page={{ data1.previous_page_number }}">Previous</a>
        {% endif %}

        <span>Page {{ data1.number }} of {{ data1.paginator.num_pages }}</span>

        {% if data1.has_next %}
            <a href="?page={{ data1.next_page_number }}">Next</a>
            <a href="?page={{ data1.paginator.num_pages }}">Last</a>
        {% endif %}
    </span>
</div>
{% endblock %}

templates/list_consignee.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="consignorName">Consignee name:</label>
        <input type="text" id="consignorName" name="consignee_name">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered" id="despatchTable">
        <thead>
        <tr>
            <th>Consignee Name</th>
            <th>Address</th>
            <th>Phone number</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.consignee_name}}</td>
                <td>{{x.consignee_address}}</td>
                <td>{{x.consignee_phone}}</td>
                <td>{{x.consignee_status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href=/edit_consignee/{{x.consignee_id}}><ion-icon name="create-outline"></ion-icon></a></button>
                    <button class="btn btn-sm btn-danger"><a href=/delete_consignee/{{x.consignee_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/list_consignor.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="consignorName">Consignor name:</label>
        <input type="text" id="consignorName" name="consignor_name">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered" id="despatchTable">
        <thead>
        <tr>
            <th>Consignor Name</th>
            <th>Address</th>
            <th>Phone number</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.consignor_name}}</td>
                <td>{{x.consignor_address}}</td>
                <td>{{x.consignor_phone}}</td>
                <td>{{x.consignor_status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href=/edit_consignor/{{x.consignor_id}}><ion-icon name="create-outline"></ion-icon></a></button>
                    <button class="btn btn-sm btn-danger"><a href=/delete_consignor/{{x.consignor_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/list_driver.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="driver_name">Driver:</label>
        <input type="text" id="driver_name" name="driver_name">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered" id="despatchTable">
        <thead>
        <tr>
            <th>Driver</th>
            <th>Address</th>
            <th>Phone Number</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.driver_name}}</td>
                <td>{{x.driver_address}}</td>
                <td>{{x.driver_phone}}</td>
                <td>{{x.driver_status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href=/edit_driver/{{x.driver_id}}><ion-icon name="create-outline"></ion-icon></a></button>
                    <button class="btn btn-sm btn-danger"><a href=/delete_driver/{{x.driver_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/list_user.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered" id="despatchTable">
        <thead>
        <tr>
            <th>Username</th>
            <th>Designation</th>
            <th>Password</th>
            <th>Phone number</th>
            <th>Email</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.username}}</td>
                <td>{{x.designation.designation}}</td>
                <td>{{x.password}}</td>
                <td>{{x.phone_number}}</td>
                <td>{{x.email}}</td>
                <td>{{x.user_status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href=/edit_user/{{x.user_id}}><ion-icon name="create-outline"></ion-icon></a></button>
                    <button class="btn btn-sm btn-danger"><a href=/delete_user/{{x.user_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/list_vehicle.html
{% extends 'dashboard.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% if messages%}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            {{ message }}
        </div>
    {% endfor%}
    {% endif%}
    <div class="search-box">
        <h4 style="font-weight: bold;">Search</h4>
        <label for="driver_name">Driver:</label>
        <input type="text" id="driver_name" name="driver_name">
        <button type="submit" class="btn btn-primary" style="background-color: #dc3545;">Search</button>
    </div>
</form>
<div class="table-container">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Model</th>
            <th>Vehicle Number</th>
            <th>Active</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for x in data1 %}
            <tr>
                <td>{{x.vehicle_name}}</td>
                <td>{{x.vehicle_number}}</td>
                <td>{{x.vehicle_status}}</td>
                <td>
                    <button class="btn btn-sm btn-warning"><a href=/edit_vehicle/{{x.vehicle_id}}><ion-icon name="create-outline"></ion-icon></a></button>
                    <button class="btn btn-sm btn-danger"><a href=/delete_vehicle/{{x.vehicle_id}}><ion-icon name="trash-outline"></ion-icon></a></button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}